# Generated by Django 5.2.6 on 2025-11-02 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nombre', models.CharField(default='Sin nombre', max_length=100)),
                ('codigo_clientes', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('correo', models.EmailField(help_text='Ingrese una dirección de email válida', max_length=254)),
                ('condicion_iva', models.CharField(choices=[('Monotributo', 'Monotributo'), ('Inscripto', 'Inscripto'), ('NoInscripto', 'NoInscripto'), ('Exento', 'Exento')], max_length=11)),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(default='Sin direccion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('dni_empleado', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('codigo_proveedores', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('correo', models.EmailField(help_text='Ingrese una dirección de email válida', max_length=254)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('codigo', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('porcentaje_recargo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('codigo_vehiculos', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=30)),
                ('ano_fabricacion', models.SmallIntegerField()),
                ('marca', models.CharField(max_length=30)),
                ('motor', models.CharField(max_length=10, null=True)),
                ('tipo_vehiculo', models.CharField(db_index=True, max_length=20)),
                ('tipo_semirremolque', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('nro_factura', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('cheque', 'cheque'), ('transferencia', 'transferencia'), ('credito', 'credito'), ('debito', 'debito')], max_length=15)),
                ('cliente_participa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('empleado_hace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Remito_Proveedores',
            fields=[
                ('nro_remito', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pagado', models.CharField(choices=[('si', 'si'), ('no', 'no')], max_length=3)),
                ('proveedor_proviene_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('nro_pago', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_parcial', models.DecimalField(decimal_places=2, max_digits=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('cheque', 'cheque'), ('transferencia', 'transferencia'), ('credito', 'credito'), ('debito', 'debito')], max_length=15)),
                ('remito_se_efectuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.remito_proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Telefonos_Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nro_remito_contiene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.remito_proveedores')),
                ('codigo_contiene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuestos')),
            ],
            options={
                'indexes': [models.Index(fields=['codigo_contiene', 'nro_remito_contiene'], name='api_contien_codigo__8a668d_idx')],
                'unique_together': {('codigo_contiene', 'nro_remito_contiene')},
            },
        ),
        migrations.CreateModel(
            name='SeFacturanEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('codigo_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuestos')),
                ('nro_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facturas')),
            ],
            options={
                'indexes': [models.Index(fields=['nro_factura', 'codigo_repuesto'], name='api_sefactu_nro_fac_230c34_idx')],
                'unique_together': {('nro_factura', 'codigo_repuesto')},
            },
        ),
        migrations.CreateModel(
            name='Suministra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_origen', models.CharField(db_index=True, max_length=20)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_repuesto_suministrado', models.DateField(default='2010-01-01')),
                ('proveedor_suministra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedores')),
                ('repuesto_suministra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuestos')),
            ],
            options={
                'indexes': [models.Index(fields=['repuesto_suministra', 'proveedor_suministra'], name='api_suminis_repuest_5777bc_idx')],
                'unique_together': {('repuesto_suministra', 'proveedor_suministra')},
            },
        ),
        migrations.CreateModel(
            name='Telefonos_Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
            options={
                'unique_together': {('cliente', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Telefonos_Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedores')),
            ],
            options={
                'unique_together': {('proveedor', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Pertenece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_codigo_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuestos')),
                ('v_codigo_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculos')),
            ],
            options={
                'indexes': [models.Index(fields=['v_codigo_pertenece', 'r_codigo_pertenece'], name='api_pertene_v_codig_00ed0d_idx')],
                'unique_together': {('v_codigo_pertenece', 'r_codigo_pertenece')},
            },
        ),
    ]
