# Generated by Django 5.2.6 on 2025-09-27 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('nombre', models.CharField(default='Sin nombre', max_length=100)),
                ('codigo_clientes', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('correo', models.EmailField(help_text='Ingrese una dirección de email válida', max_length=254)),
                ('condicion_iva', models.CharField(choices=[('Monotributo', 'Monotributo'), ('Inscripto', 'Inscripto'), ('NoInscripto', 'NoInscripto'), ('Exento', 'Exento')], max_length=11)),
                ('razon_social', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(default='Sin direccion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('dni_empleado', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('codigo_proveedores', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('correo', models.EmailField(help_text='Ingrese una dirección de email válida', max_length=254)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('codigo', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('tipo', models.CharField(max_length=100, null=True)),
                ('porcentaje_recargo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('codigo_vehiculos', models.CharField(db_index=True, max_length=30, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=30)),
                ('ano_fabricacion', models.DateField()),
                ('marca', models.CharField(max_length=30)),
                ('motor', models.CharField(max_length=10, null=True)),
                ('tipo_vehiculo', models.CharField(db_index=True, max_length=20)),
                ('tipo_semirremolque', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefonos_Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Telefonos_Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
            ],
            options={
                'unique_together': {('cliente', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Telefonos_Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedores')),
            ],
            options={
                'unique_together': {('proveedor', 'numero')},
            },
        ),
    ]
