# Generated by Django 5.2.6 on 2025-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuestos',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=100)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('tipo', models.CharField(null=True)),
                ('porcentaje_recargo', models.IntegerField()),
            ],
        ),
    ]
