# Generated by Django 5.2.6 on 2025-09-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito_Proveedores',
            fields=[
                ('nro_remito', models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pagado', models.CharField(choices=[('si', 'si'), ('no', 'no')], max_length=3)),
                ('proveedor_proviene_de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('nro_pago', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_parcial', models.DecimalField(decimal_places=2, max_digits=20)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('cheque', 'cheque'), ('transferencia', 'transferencia'), ('credito', 'credito'), ('debito', 'debito')], max_length=15)),
                ('remito_se_efectuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.remito_proveedores')),
            ],
        ),
        migrations.CreateModel(
            name='Contiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_contiene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuestos')),
                ('nro_remito_contiene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.remito_proveedores')),
            ],
            options={
                'indexes': [models.Index(fields=['codigo_contiene', 'nro_remito_contiene'], name='api_contien_codigo__8a668d_idx')],
                'unique_together': {('codigo_contiene', 'nro_remito_contiene')},
            },
        ),
        migrations.CreateModel(
            name='suministra',
            fields=[
                ('codigo_origen', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('proveedor_suministra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proveedores')),
                ('repuesto_suministra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuestos')),
            ],
            options={
                'indexes': [models.Index(fields=['repuesto_suministra', 'proveedor_suministra'], name='api_suminis_repuest_5777bc_idx')],
                'unique_together': {('repuesto_suministra', 'proveedor_suministra')},
            },
        ),
    ]
