# Generated by Django 5.2.6 on 2025-11-02 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='cliente_participa_cuit_log',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='facturas',
            name='cliente_participa_direccion_log',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='facturas',
            name='cliente_participa_razon_social_log',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='facturas',
            name='empleado_hace_log',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='sefacturanen',
            name='codigo_repuesto_log',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sefacturanen',
            name='descripcion_repuesto_log',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='cliente_participa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.clientes'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='empleado_hace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empleados'),
        ),
        migrations.AlterField(
            model_name='sefacturanen',
            name='codigo_repuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.repuestos'),
        ),
    ]
