# Generated by Django 5.2.6 on 2025-11-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuestos',
            old_name='porcentaje_recarg',
            new_name='porcentaje_recargo',
        ),
    ]
