# Generated by Django 5.2.6 on 2025-10-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suministra',
            name='fecha_repuesto_suministrado',
            field=models.DateField(default='2010-01-01'),
        ),
    ]
