# Generated by Django 5.2.6 on 2025-09-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='repuestos',
            name='tipo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
