# Generated by Django 5.2.6 on 2025-10-25 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remito_proveedores_pagos_contiene_suministra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('nro_factura', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'efectivo'), ('cheque', 'cheque'), ('transferencia', 'transferencia'), ('credito', 'credito'), ('debito', 'debito')], max_length=15)),
                ('cliente_participa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('empleado_hace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='Pertenece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuestos')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='SeFacturanEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('codigo_repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.repuestos')),
                ('nro_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facturas')),
            ],
            options={
                'indexes': [models.Index(fields=['nro_factura', 'codigo_repuesto'], name='api_sefactu_nro_fac_230c34_idx')],
                'unique_together': {('nro_factura', 'codigo_repuesto')},
            },
        ),
    ]
