# Generated by Django 5.2.6 on 2025-10-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_suministra_fecha_repuesto_suministrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='nro_factura',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
