# Generated by Django 5.2.6 on 2025-09-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_repuestos_precio_venta_alter_repuestos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='codigo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
