# Generated by Django 5.2.6 on 2025-11-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_facturas_nro_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='ano_fabricacion',
            field=models.CharField(max_length=4),
        ),
    ]
