# Generated by Django 5.2.6 on 2025-10-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_facturas_pertenece_sefacturanen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pertenece',
            old_name='repuesto',
            new_name='R_Codigo_pertenece',
        ),
        migrations.RenameField(
            model_name='pertenece',
            old_name='vehiculo',
            new_name='V_Codigo_pertenece',
        ),
    ]
