# Generated by Django 5.2.6 on 2025-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_vehiculos_ano_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='ano_fabricacion',
            field=models.SmallIntegerField(),
        ),
    ]
