# Generated by Django 5.2.6 on 2025-09-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clientes_empleados_proveedores_vehiculos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(default='Sin direccion', max_length=200),
        ),
    ]
