# Generated by Django 5.2.6 on 2025-10-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_repuesto_pertenece_r_codigo_pertenece_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pertenece',
            unique_together={('V_Codigo_pertenece', 'R_Codigo_pertenece')},
        ),
        migrations.AddIndex(
            model_name='pertenece',
            index=models.Index(fields=['V_Codigo_pertenece', 'R_Codigo_pertenece'], name='api_pertene_V_Codig_9e923b_idx'),
        ),
    ]
