# Generated by Django 5.2.6 on 2025-11-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vehiculos_ano_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='codigo_clientes',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='codigo_proveedores',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
