# Generated by Django 5.2.6 on 2025-09-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_clientes_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
