# Generated by Django 5.2.6 on 2025-09-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_clientes_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefonos_clientes',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='telefonos_empleados',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='telefonos_proveedores',
            name='tipo',
        ),
    ]
