# Generated by Django 5.2.6 on 2025-11-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_clientes_codigo_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuestos',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
