# Generated by Django 5.2.6 on 2025-11-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_repuestos_precio_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuestos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
